### ISSUE TITLE
Boolean has compilation issues

### ISSUE THREAD

**Issue by Comdec35000** [quark-lang/quark#12]
**Describe the bug** A clear and concise description of what the bug is.

Booleans from std seems to not be correctly declared in the compiled code : when running the compiled version with NodeJS 16.8.0 we get the error "ReferenceError: $true is not defined"

**To Reproduce** Steps to reproduce the behavior:

Create a simple program like so :
```clojure
(defn main [] (print (to_string(true)))
```

**Desktop (please complete the following information):**

-   OS: MacOS Monterey 12.1
-   Quark 1.0.0

**Comment by thomasvergne** [comment]
FIxed in [v1.1.0](https://github.com/quark-lang/quark/releases/tag/v1.1.0) of Quark!
